import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from groq import Groq


# Load .env file
load_dotenv()


# Create FastAPI app
app = FastAPI()


# Allow frontend to communicate with backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Groq client
client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


# Request model
class PostRequest(BaseModel):
    topic: str
    style: str = "Professional"
    length: str = "Medium"


# Home route
@app.get("/")
def home():
    return {
        "message": "LinkedIn Post Generator API"
    }


# Generate LinkedIn post
@app.post("/generate-post")
def generate_post(request: PostRequest):

    prompt = f"""
Create a high-quality LinkedIn post.

Topic:
{request.topic}

Style:
{request.style}

Length:
{request.length}

Requirements:

- Write a professional LinkedIn post.
- Make it engaging and easy to read.
- Use short paragraphs.
- Start with a strong hook.
- Provide useful insights.
- Keep the tone suitable for LinkedIn.
- Use emojis naturally, but don't overuse them.
- End with an engaging question or call to action.
- Add 5-8 relevant hashtags.
- Do not mention that the post was generated by AI.

Length instructions:

Short:
Around 100-150 words.

Medium:
Around 200-300 words.

Long:
Around 350-500 words.

Return only the LinkedIn post.
"""


    try:

        response = client.chat.completions.create(

            model="llama-3.3-70b-versatile",

            messages=[
                {
                    "role": "system",
                    "content": "You are an expert LinkedIn content writer."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],

            temperature=0.7,

            max_tokens=1000
        )


        post = response.choices[0].message.content


        return {
            "topic": request.topic,
            "style": request.style,
            "length": request.length,
            "post": post
        }


    except Exception as e:

        return {
            "error": str(e)
        }